-- MySQL Script generated by MySQL Workbench
-- Wed Jan  4 11:36:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sklep_internetowy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sklep_internetowy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sklep_internetowy` DEFAULT CHARACTER SET utf8mb4 ;
USE `sklep_internetowy` ;

-- -----------------------------------------------------
-- Table `sklep_internetowy`.`adresy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`adresy` (
  `id_adres` INT(11) NOT NULL,
  `miasto` VARCHAR(50) NULL DEFAULT NULL,
  `miejscowość` VARCHAR(50) NULL DEFAULT NULL,
  `wojewodztwo` VARCHAR(50) NULL DEFAULT NULL,
  `powiat` VARCHAR(50) NULL DEFAULT NULL,
  `ulica` VARCHAR(50) NULL DEFAULT NULL,
  `nr_domu` INT(11) NULL DEFAULT NULL,
  `nr_lokalu` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_adres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`produkty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`produkty` (
  `id_produktu` INT(11) NOT NULL,
  `id_kategorie_produceci` INT(11) NULL DEFAULT NULL,
  `nazwa_produktu` VARCHAR(50) NULL DEFAULT NULL,
  `typ` VARCHAR(50) NULL DEFAULT NULL,
  `wersja` VARCHAR(50) NULL DEFAULT NULL,
  `opis` TEXT NULL DEFAULT NULL,
  `fotografia` VARCHAR(50) NULL DEFAULT NULL,
  `cema_netto_sprzedazy_aktualna` DECIMAL(6,2) NULL DEFAULT NULL,
  `cema_brutto_sprzedazy_aktualna` DECIMAL(6,2) NULL DEFAULT NULL,
  `cema_vat_sprzedazy_aktualna` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_produktu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`egzemplarze`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`egzemplarze` (
  `id_faktura` INT(11) NOT NULL,
  `kod_produktu` VARCHAR(50) NULL DEFAULT NULL,
  `cena_netto_zakupu` VARCHAR(50) NULL DEFAULT NULL,
  `cena_brutto_zakupu` VARCHAR(50) NULL DEFAULT NULL,
  `cena_vat_zakupu` VARCHAR(50) NULL DEFAULT NULL,
  `data_zakupu` DATE NULL DEFAULT NULL,
  `data_sprzedarzy` DATE NULL DEFAULT NULL,
  `czy_sprzedano` VARCHAR(50) NULL DEFAULT NULL,
  `produkty_id_produktu` INT(11) NOT NULL,
  PRIMARY KEY (`id_faktura`, `produkty_id_produktu`),
  INDEX `fk_egzemplarze_produkty1_idx` (`produkty_id_produktu` ASC) VISIBLE,
  CONSTRAINT `fk_egzemplarze_produkty1`
    FOREIGN KEY (`produkty_id_produktu`)
    REFERENCES `sklep_internetowy`.`produkty` (`id_produktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`faktury`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`faktury` (
  `id_faktura` INT(11) NOT NULL,
  `nr_faktury` VARCHAR(50) NULL DEFAULT NULL,
  `data_sprzedazy` DATE NULL DEFAULT NULL,
  `wartosc_netto` VARCHAR(50) NULL DEFAULT NULL,
  `wartosc_brutto` VARCHAR(50) NULL DEFAULT NULL,
  `wartosc_vat` VARCHAR(50) NULL DEFAULT NULL,
  `nazwa_banku` VARCHAR(50) NULL DEFAULT NULL,
  `forma_platnosci` VARCHAR(50) NULL DEFAULT NULL,
  `rodzaj_dokumenty` VARCHAR(50) NULL DEFAULT NULL,
  `egzemplarze_id_faktura` INT(11) NOT NULL,
  `egzemplarze_produkty_id_produktu` INT(11) NOT NULL,
  PRIMARY KEY (`id_faktura`),
  INDEX `fk_faktury_egzemplarze1_idx` (`egzemplarze_id_faktura` ASC, `egzemplarze_produkty_id_produktu` ASC) VISIBLE,
  CONSTRAINT `fk_faktury_egzemplarze1`
    FOREIGN KEY (`egzemplarze_id_faktura` , `egzemplarze_produkty_id_produktu`)
    REFERENCES `sklep_internetowy`.`egzemplarze` (`id_faktura` , `produkty_id_produktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`galeria_zdiec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`galeria_zdiec` (
  `id_zdięcie` INT(11) NOT NULL,
  `id_produktu` INT(11) NULL,
  `nazwa_jpg` VARCHAR(50) NULL DEFAULT NULL,
  `data_dodania` DATE NULL DEFAULT NULL,
  `produkty_id_produktu` INT(11) NOT NULL,
  PRIMARY KEY (`id_zdięcie`),
  INDEX `fk_galeria_zdiec_produkty_idx` (`produkty_id_produktu` ASC) VISIBLE,
  CONSTRAINT `fk_galeria_zdiec_produkty`
    FOREIGN KEY (`produkty_id_produktu`)
    REFERENCES `sklep_internetowy`.`produkty` (`id_produktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`kategorie` (
  `id_kategoria` INT(11) NOT NULL,
  `nazwa_kategorii` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_kategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`kontakty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`kontakty` (
  `id_kontakt` INT(11) NOT NULL,
  `nr_tel_1` VARCHAR(50) NULL DEFAULT NULL,
  `nr_tel_2` VARCHAR(50) NULL DEFAULT NULL,
  `fax` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `www` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_kontakt`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`klienci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`klienci` (
  `id_klient` INT(11) NOT NULL,
  `login` VARCHAR(50) NULL DEFAULT NULL,
  `nazwa_firmy` VARCHAR(50) NULL DEFAULT NULL,
  `regon` VARCHAR(50) NULL DEFAULT NULL,
  `nip` INT(11) NULL DEFAULT NULL,
  `nazwisko` VARCHAR(50) NULL DEFAULT NULL,
  `imie` VARCHAR(50) NULL DEFAULT NULL,
  `rodzaj_klienta` VARCHAR(50) NULL DEFAULT NULL,
  `kontakty_id_kontakt` INT(11) NOT NULL,
  `faktury_id_faktura` INT(11) NOT NULL,
  PRIMARY KEY (`id_klient`),
  INDEX `fk_klienci_kontakty1_idx` (`kontakty_id_kontakt` ASC) VISIBLE,
  INDEX `fk_klienci_faktury1_idx` (`faktury_id_faktura` ASC) VISIBLE,
  CONSTRAINT `fk_klienci_kontakty1`
    FOREIGN KEY (`kontakty_id_kontakt`)
    REFERENCES `sklep_internetowy`.`kontakty` (`id_kontakt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_klienci_faktury1`
    FOREIGN KEY (`faktury_id_faktura`)
    REFERENCES `sklep_internetowy`.`faktury` (`id_faktura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`pracownicy` (
  `id_pracownik` INT(11) NOT NULL,
  `login` VARCHAR(50) NULL DEFAULT NULL,
  `md5_haslo` VARCHAR(50) NULL DEFAULT NULL,
  `imie` VARCHAR(50) NULL DEFAULT NULL,
  `nazwisko` VARCHAR(50) NULL DEFAULT NULL,
  `uprawnienie` VARCHAR(50) NULL DEFAULT NULL,
  `konto_aktywne` VARCHAR(50) NULL DEFAULT NULL,
  `data_zatrudnienia` DATE NULL DEFAULT NULL,
  `data_zwolnienia` DATE NULL DEFAULT NULL,
  `adresy_id_adres` INT(11) NOT NULL,
  `kontakty_id_kontakt` INT(11) NOT NULL,
  PRIMARY KEY (`id_pracownik`),
  INDEX `fk_pracownicy_adresy1_idx` (`adresy_id_adres` ASC) VISIBLE,
  INDEX `fk_pracownicy_kontakty1_idx` (`kontakty_id_kontakt` ASC) VISIBLE,
  CONSTRAINT `fk_pracownicy_adresy1`
    FOREIGN KEY (`adresy_id_adres`)
    REFERENCES `sklep_internetowy`.`adresy` (`id_adres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pracownicy_kontakty1`
    FOREIGN KEY (`kontakty_id_kontakt`)
    REFERENCES `sklep_internetowy`.`kontakty` (`id_kontakt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`producęci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`producęci` (
  `id_producenta` INT(11) NOT NULL,
  `nazwa_producenta` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_producenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`zamówienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`zamówienia` (
  `id_zamowienia` INT(11) NOT NULL,
  `data_zalozenia_zamowienia` DATE NULL DEFAULT NULL,
  `czy_przjeto_zamowienia` VARCHAR(50) NULL DEFAULT NULL,
  `data_przyjecia_zamowienia` DATE NULL DEFAULT NULL,
  `zaplacono` VARCHAR(50) NULL DEFAULT NULL,
  `data_wysylki` DATE NULL DEFAULT NULL,
  `czy_zamowienie_zrealizowano` VARCHAR(50) NULL DEFAULT NULL,
  `data_realizacji_zamowienia` DATE NULL DEFAULT NULL,
  `klienci_id_klient` INT(11) NOT NULL,
  PRIMARY KEY (`id_zamowienia`),
  INDEX `fk_zamówienia_klienci1_idx` (`klienci_id_klient` ASC) VISIBLE,
  CONSTRAINT `fk_zamówienia_klienci1`
    FOREIGN KEY (`klienci_id_klient`)
    REFERENCES `sklep_internetowy`.`klienci` (`id_klient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`kategorie_has_producęci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`kategorie_has_producęci` (
  `kategorie_id_kategoria` INT(11) NOT NULL,
  `producęci_id_producenta` INT(11) NOT NULL,
  `produkty_id_produktu` INT(11) NOT NULL,
  PRIMARY KEY (`kategorie_id_kategoria`, `producęci_id_producenta`),
  INDEX `fk_kategorie_has_producęci_producęci1_idx` (`producęci_id_producenta` ASC) VISIBLE,
  INDEX `fk_kategorie_has_producęci_kategorie1_idx` (`kategorie_id_kategoria` ASC) VISIBLE,
  INDEX `fk_kategorie_has_producęci_produkty1_idx` (`produkty_id_produktu` ASC) VISIBLE,
  CONSTRAINT `fk_kategorie_has_producęci_kategorie1`
    FOREIGN KEY (`kategorie_id_kategoria`)
    REFERENCES `sklep_internetowy`.`kategorie` (`id_kategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kategorie_has_producęci_producęci1`
    FOREIGN KEY (`producęci_id_producenta`)
    REFERENCES `sklep_internetowy`.`producęci` (`id_producenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kategorie_has_producęci_produkty1`
    FOREIGN KEY (`produkty_id_produktu`)
    REFERENCES `sklep_internetowy`.`produkty` (`id_produktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`zamówienia_has_produkty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`zamówienia_has_produkty` (
  `zamówienia_id_zamowienia` INT(11) NOT NULL,
  `produkty_id_produktu` INT(11) NOT NULL,
  PRIMARY KEY (`zamówienia_id_zamowienia`, `produkty_id_produktu`),
  INDEX `fk_zamówienia_has_produkty_produkty1_idx` (`produkty_id_produktu` ASC) VISIBLE,
  INDEX `fk_zamówienia_has_produkty_zamówienia1_idx` (`zamówienia_id_zamowienia` ASC) VISIBLE,
  CONSTRAINT `fk_zamówienia_has_produkty_zamówienia1`
    FOREIGN KEY (`zamówienia_id_zamowienia`)
    REFERENCES `sklep_internetowy`.`zamówienia` (`id_zamowienia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamówienia_has_produkty_produkty1`
    FOREIGN KEY (`produkty_id_produktu`)
    REFERENCES `sklep_internetowy`.`produkty` (`id_produktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sklep_internetowy`.`klienci_has_adresy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklep_internetowy`.`klienci_has_adresy` (
  `klienci_id_klient` INT(11) NOT NULL,
  `adresy_id_adres` INT(11) NOT NULL,
  PRIMARY KEY (`klienci_id_klient`, `adresy_id_adres`),
  INDEX `fk_klienci_has_adresy_adresy1_idx` (`adresy_id_adres` ASC) VISIBLE,
  INDEX `fk_klienci_has_adresy_klienci1_idx` (`klienci_id_klient` ASC) VISIBLE,
  CONSTRAINT `fk_klienci_has_adresy_klienci1`
    FOREIGN KEY (`klienci_id_klient`)
    REFERENCES `sklep_internetowy`.`klienci` (`id_klient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_klienci_has_adresy_adresy1`
    FOREIGN KEY (`adresy_id_adres`)
    REFERENCES `sklep_internetowy`.`adresy` (`id_adres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
